export enum granularity {
  MINUTE = 'minute',
  HOUR = 'hour',
  DAY = 'day',
  WEEK = 'week',
  MONTH = 'month',
  QUARTER = 'quarter',
  YEAR = 'year',
  MINUTE_OF_HOUR = 'minute-of-hour',
  HOUR_OF_DAY = 'hour-of-day',
  DAY_OF_WEEK = 'day-of-week',
  DAY_OF_MONTH = 'day-of-month',
  DAY_OF_YEAR = 'day-of-year',
  WEEK_OF_YEAR = 'week-of-year',
  MONTH_OF_YEAR = 'month-of-year',
  QUARTER_OF_YEAR = 'quarter-of-year',
}
